name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest  
    permissions:
      contents: read
      id-token: write

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
      ARTIFACT_REGISTRY_REPO: ${{ secrets.ARTIFACT_REGISTRY_REPO }}
      CLOUD_RUN_SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_NAME }}
      REGISTRY_REGION: us-central1
      IMAGE_TAG: app:latest

    steps: 
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Build Image
        run: scripts/buildprod.sh  

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: '>= 363.0.0'

      - name: Use gcloud CLI
        run: gcloud info
        
      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ env.REGISTRY_REGION }}-docker.pkg.dev

      - name: Submit Image to Artifact Registry
        run: |
          gcloud builds submit \
            --tag ${{ env.REGISTRY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_TAG }} \
            .

      - name: Install Goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest
        
      - name: Migrate Database
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.CLOUD_RUN_SERVICE_NAME }} \
            --image ${{ env.REGISTRY_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REGISTRY_REPO }}/${{ env.IMAGE_TAG }} \
            --region ${{ env.REGISTRY_REGION }} \
            --allow-unauthenticated \
            --project ${{ env.GCP_PROJECT_ID }} \
            --max-instances=4