name: CD

on:
  push:
    branches: [main]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest  
    permissions:
      contents: read
      id-token: write

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps: 
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.26.0"

      - name: Build Image
        run: scripts/buildprod.sh  

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/253869999413/locations/global/workloadIdentityPools/notely-pool/providers/notely-provider
          service_account: cloud-run-deployer@celtic-sunlight-443602-k1.iam.gserviceaccount.com

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3
        with:
          version: '>= 363.0.0'

      - name: Use gcloud CLI
        run: gcloud info
        
      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Submit Image to Artifact Registry
        run: |
          gcloud builds submit \
            --tag us-central1-docker.pkg.dev/celtic-sunlight-443602-k1/notely-ar-repo/app:latest \
            .
            

      # - name: Install Goose
      #   run: go install github.com/pressly/goose/v3/cmd/goose@latest
        
      # - name: Migrate Database
      #   run: ./scripts/migrateup.sh

      # - name: Deploy to Cloud Run
      #   run: gcloud run deploy notely --image us-central1-docker.pkg.dev/celtic-sunlight-443602-k1/notely-ar-repo/app:latest --region us-central1 --allow-unauthenticated --project 253869999413 --max-instances=4